var express=require('express')
var app=express()
var router=require('./server/api')
var bodyparser=require('body-parser')
app.use(bodyparser.json())
app.use(express.static('./dist'))
app.use('/api',router)
app.listen(3000,()=>{
    console.log('listening at 3000')
})