NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.customer.supplychain.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.customer.supplychain.com-cert.pem
    OrganizationalUnitIdentifier: peer
